//! Structured simulation event tracing.
//!
//! Every observable state change in the simulator can emit a [`SimEvent`].
//! Events are delivered to an [`EventSink`] implementation chosen at
//! construction time:
//!
//! - [`NullEventSink`] — zero overhead; discards all events.
//! - [`VecEventSink`] — collects events for post-run inspection; used in tests.
//!
//! ## Overhead control
//!
//! Tracing is cheap but not free.  Benchmark mode should use [`NullEventSink`]
//! to avoid the per-event allocation in [`VecEventSink`].  The [`EventSink`]
//! trait is object-safe so a `Box<dyn EventSink>` can be swapped at runtime.
//!
//! ## Dashboard integration
//!
//! A future Phoenix LiveView dashboard will subscribe to events via a channel
//! sender stored in a custom [`EventSink`] implementation.  The API here
//! (trait object + `emit`) is deliberately minimal so that sink can be added
//! without changing component APIs.

use std::sync::{Arc, Mutex};

// ---------------------------------------------------------------------------
// SimEvent
// ---------------------------------------------------------------------------

/// A single observable event emitted by a simulator component.
///
/// Events carry the simulator timestamp ([`clock_ns`][SimEvent::clock_ns]) so
/// they can be replayed or correlated with metrics after the run.
#[derive(Debug, Clone)]
pub struct SimEvent {
    /// Simulator clock value when the event was emitted (nanoseconds).
    pub clock_ns: u64,
    /// The kind of event and its payload.
    pub kind: SimEventKind,
}

/// The kind of event emitted by a simulator component.
#[derive(Debug, Clone)]
pub enum SimEventKind {
    /// A packet was generated by a virtual NIC.
    PacketGenerated {
        /// Source NIC name.
        nic: &'static str,
        /// Total packet bytes including all headers.
        len: usize,
        /// Packet sequence number within this NIC.
        seq: u64,
    },
    /// A packet was dropped by fault injection.
    PacketDropped {
        /// Source NIC name.
        nic: &'static str,
        /// Sequence number of the dropped packet.
        seq: u64,
    },
    /// A packet payload was corrupted by fault injection.
    PacketCorrupted {
        /// Source NIC name.
        nic: &'static str,
        /// Sequence number of the corrupted packet.
        seq: u64,
    },
    /// A storage record was successfully read.
    RecordRead {
        /// Backend name (e.g. `"file"`).
        backend: &'static str,
        /// Byte offset of the record in the source file.
        offset: u64,
        /// Record size in bytes.
        len: usize,
    },
    /// A record was dropped by fault injection on the storage path.
    RecordDropped {
        /// Backend name.
        backend: &'static str,
        /// Byte offset of the dropped record.
        offset: u64,
    },
    /// A slot was written to a shared-memory ring.
    SlotWritten {
        /// Ring identifier (e.g. a sink name).
        ring: &'static str,
        /// Slot sequence number.
        seq: u64,
    },
    /// A consumer read a slot from a shared-memory ring.
    ConsumerRead {
        /// Ring identifier.
        ring: &'static str,
        /// Slot sequence number.
        seq: u64,
    },
    /// A ring was full; a write was dropped.
    QueueOverflow {
        /// Ring identifier.
        ring: &'static str,
    },
    /// A parser / decoder failed on one record.
    ParserError {
        /// Human-readable description.
        message: String,
    },
    /// A placement decision was made.
    PlacementDecision {
        /// Name of the placement strategy.
        strategy: &'static str,
        /// Number of messages routed in this decision.
        count: usize,
    },
    /// The scheduler completed one tick.
    TickCompleted {
        /// Tick number (1-based).
        tick: u64,
        /// Wall-clock nanoseconds the tick took.
        duration_ns: u64,
    },
    /// The simulator started.
    SimulatorStarted {
        /// Scenario name.
        scenario: String,
    },
    /// The simulator stopped.
    SimulatorStopped {
        /// Total ticks completed.
        ticks: u64,
        /// Total nanoseconds elapsed (virtual or real).
        elapsed_ns: u64,
    },
}

// ---------------------------------------------------------------------------
// EventSink trait
// ---------------------------------------------------------------------------

/// Receives simulation events.
///
/// All implementations must be `Send + 'static` so they can be stored in
/// simulator components that cross thread boundaries.
pub trait EventSink: Send + Sync + 'static {
    /// Deliver an event to the sink.
    ///
    /// This method is called on the hot path in benchmark mode only when the
    /// caller uses a non-null sink.  Keep implementations fast.
    fn emit(&self, event: SimEvent);
}

// ---------------------------------------------------------------------------
// NullEventSink
// ---------------------------------------------------------------------------

/// Discards all events.  Zero overhead; use for benchmarks.
#[derive(Debug, Default, Clone, Copy)]
pub struct NullEventSink;

impl EventSink for NullEventSink {
    #[inline(always)]
    fn emit(&self, _event: SimEvent) {}
}

// ---------------------------------------------------------------------------
// VecEventSink
// ---------------------------------------------------------------------------

/// Collects all events into a `Vec` for post-run inspection.
///
/// Suitable for tests and educational mode.  Not recommended for benchmarks.
///
/// Clone the `Arc` to share the sink across multiple components and call
/// [`events`][Self::events] after the run.
#[derive(Debug, Clone, Default)]
pub struct VecEventSink {
    events: Arc<Mutex<Vec<SimEvent>>>,
}

impl VecEventSink {
    /// Create a new empty sink.
    pub fn new() -> Self {
        Self::default()
    }

    /// Return all collected events, consuming the lock.
    pub fn events(&self) -> Vec<SimEvent> {
        self.events.lock().unwrap().clone()
    }

    /// Number of events collected so far.
    pub fn len(&self) -> usize {
        self.events.lock().unwrap().len()
    }

    /// `true` if no events have been collected.
    pub fn is_empty(&self) -> bool {
        self.events.lock().unwrap().is_empty()
    }
}

impl EventSink for VecEventSink {
    fn emit(&self, event: SimEvent) {
        self.events.lock().unwrap().push(event);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn null_sink_accepts_any_event() {
        let sink = NullEventSink;
        sink.emit(SimEvent { clock_ns: 0, kind: SimEventKind::SimulatorStarted { scenario: "test".into() } });
        // no panic = pass
    }

    #[test]
    fn vec_sink_collects_events() {
        let sink = VecEventSink::new();
        assert!(sink.is_empty());
        sink.emit(SimEvent {
            clock_ns: 100,
            kind: SimEventKind::PacketGenerated { nic: "nic0", len: 64, seq: 1 },
        });
        sink.emit(SimEvent {
            clock_ns: 200,
            kind: SimEventKind::PacketDropped { nic: "nic0", seq: 2 },
        });
        assert_eq!(sink.len(), 2);
    }

    #[test]
    fn vec_sink_events_returns_all() {
        let sink = VecEventSink::new();
        for i in 0..5u64 {
            sink.emit(SimEvent {
                clock_ns: i * 1000,
                kind: SimEventKind::TickCompleted { tick: i + 1, duration_ns: 100 },
            });
        }
        let events = sink.events();
        assert_eq!(events.len(), 5);
        assert_eq!(events[0].clock_ns, 0);
        assert_eq!(events[4].clock_ns, 4000);
    }

    #[test]
    fn vec_sink_is_clonable_and_shared() {
        let sink = VecEventSink::new();
        let sink2 = sink.clone();
        sink.emit(SimEvent { clock_ns: 1, kind: SimEventKind::QueueOverflow { ring: "r0" } });
        // Both handles see the same underlying vec
        assert_eq!(sink2.len(), 1);
    }
}
