//! Metric keys for the FlyBy simulator.

use flyby_core::MetricKey;

/// Metrics emitted by the simulator subsystem.
///
/// All keys are in the `"sim.*"` namespace.  Counters are cumulative since
/// the simulator was last started.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SimMetricKey {
    /// Total packets generated by all virtual NICs.
    PacketsGenerated,
    /// Packets dropped by fault injection.
    PacketsDropped,
    /// Packets deliberately corrupted by fault injection.
    PacketsCorrupted,
    /// Total storage records read by all virtual storage sources.
    RecordsRead,
    /// Records dropped on the storage path by fault injection.
    RecordsDropped,
    /// Total bytes delivered through the pipeline (packets + records).
    ThroughputBytes,
    /// Current NIC queue occupancy (fraction of capacity, 0.0–1.0).
    QueueOccupancy,
    /// Current shared-memory ring occupancy (fraction, 0.0–1.0).
    RingOccupancy,
    /// End-to-end latency in nanoseconds (last measured).
    LatencyNs,
    /// Placement decisions made by the routing layer.
    PlacementDecisions,
    /// Slot writes to shared-memory sinks.
    SinkWrites,
    /// Number of scheduler ticks completed.
    TickCount,
    /// Wall-clock nanoseconds spent on the last tick.
    TickDurationNs,
    /// Parser / decoder errors encountered.
    ParserErrors,
}

impl MetricKey for SimMetricKey {
    fn name(&self) -> &'static str {
        match self {
            Self::PacketsGenerated => "sim.packets_generated",
            Self::PacketsDropped => "sim.packets_dropped",
            Self::PacketsCorrupted => "sim.packets_corrupted",
            Self::RecordsRead => "sim.records_read",
            Self::RecordsDropped => "sim.records_dropped",
            Self::ThroughputBytes => "sim.throughput_bytes",
            Self::QueueOccupancy => "sim.queue_occupancy",
            Self::RingOccupancy => "sim.ring_occupancy",
            Self::LatencyNs => "sim.latency_ns",
            Self::PlacementDecisions => "sim.placement_decisions",
            Self::SinkWrites => "sim.sink_writes",
            Self::TickCount => "sim.tick_count",
            Self::TickDurationNs => "sim.tick_duration_ns",
            Self::ParserErrors => "sim.parser_errors",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn all_names_have_sim_prefix() {
        let keys = [
            SimMetricKey::PacketsGenerated,
            SimMetricKey::PacketsDropped,
            SimMetricKey::PacketsCorrupted,
            SimMetricKey::RecordsRead,
            SimMetricKey::RecordsDropped,
            SimMetricKey::ThroughputBytes,
            SimMetricKey::QueueOccupancy,
            SimMetricKey::RingOccupancy,
            SimMetricKey::LatencyNs,
            SimMetricKey::PlacementDecisions,
            SimMetricKey::SinkWrites,
            SimMetricKey::TickCount,
            SimMetricKey::TickDurationNs,
            SimMetricKey::ParserErrors,
        ];
        for key in keys {
            assert!(
                key.name().starts_with("sim."),
                "key {:?} = '{}' lacks 'sim.' prefix",
                key,
                key.name()
            );
        }
    }

    #[test]
    fn all_names_unique() {
        let names: HashSet<_> = [
            SimMetricKey::PacketsGenerated,
            SimMetricKey::PacketsDropped,
            SimMetricKey::PacketsCorrupted,
            SimMetricKey::RecordsRead,
            SimMetricKey::RecordsDropped,
            SimMetricKey::ThroughputBytes,
            SimMetricKey::QueueOccupancy,
            SimMetricKey::RingOccupancy,
            SimMetricKey::LatencyNs,
            SimMetricKey::PlacementDecisions,
            SimMetricKey::SinkWrites,
            SimMetricKey::TickCount,
            SimMetricKey::TickDurationNs,
            SimMetricKey::ParserErrors,
        ]
        .iter()
        .map(|k| k.name())
        .collect();
        assert_eq!(names.len(), 14);
    }
}
