//! Simulation scheduler: drives virtual time and coordinates sources.
//!
//! [`SimScheduler`] is the execution engine for a [`Scenario`].  It:
//!
//! 1. Advances virtual (or real) time one tick at a time.
//! 2. Calls `poll_batch` on all registered [`VirtualNic`]s (with tick pacing).
//! 3. Optionally pushes delivered packets into a [`VirtualSharedMemory`] ring
//!    and drains [`VirtualConsumer`]s.
//! 4. Accumulates counters into [`SimStats`] and records metrics.
//! 5. Emits a [`SimEventKind::TickCompleted`] event after each tick.
//! 6. Stops when the scenario's duration has elapsed (or when educational
//!    controls pause the run).
//!
//! ## Design
//!
//! The scheduler never sleeps between ticks in virtual-time mode — the
//! simulation runs as fast as the CPU allows.  Latency spikes from fault
//! injection advance virtual time without sleeping.
//!
//! The scheduler is deliberately free of generics over the NIC type so that
//! it can hold multiple heterogeneous NICs — it accepts `Box<dyn DynNic>`.

use std::sync::Arc;
use std::time::{Duration, Instant};

use flyby_core::{MetricsCollector, NullCollector};
use flyby_net::RawBatch;

use crate::clock::SimClock;
use crate::consumer::VirtualConsumer;
use crate::events::{EventSink, NullEventSink, SimEvent, SimEventKind};
use crate::metrics::SimMetricKey;
use crate::ring::VirtualSharedMemory;
use crate::scenario::Scenario;

/// Cumulative statistics for one simulation run.
#[derive(Debug, Clone, Default)]
pub struct SimStats {
    /// Total scheduler ticks completed.
    pub ticks: u64,
    /// Total packets generated by all virtual NICs (pre-drop).
    pub packets_generated: u64,
    /// Packets dropped by fault injection.
    pub packets_dropped: u64,
    /// Packets corrupted by fault injection.
    pub packets_corrupted: u64,
    /// Packets written into the virtual shared-memory ring.
    pub slots_written: u64,
    /// Packets read by virtual consumers.
    pub slots_consumed: u64,
    /// Ring overflows (writes dropped because the ring was full).
    pub ring_overflows: u64,
    /// Wall-clock duration of the run.
    pub elapsed: Duration,
    /// Final virtual (or real) clock reading in nanoseconds.
    pub clock_ns: u64,
}

/// Object-safe trait for type-erased NICs inside the scheduler.
pub trait DynNic: Send {
    /// Initialise the NIC (open sockets, allocate buffers).
    fn init(&mut self) -> flyby_core::Result<()>;
    /// Shut down the NIC and release resources.
    fn shutdown(&mut self) -> flyby_core::Result<()>;
    /// Provide tick context before polling.
    fn set_tick_context(&mut self, tick_ns: u64, clock_ns: u64);
    /// Poll for up to `batch.capacity()` packets, returning how many were written.
    fn poll(&mut self, batch: &mut RawBatch) -> flyby_core::Result<usize>;
    /// Drain accumulated latency-spike nanoseconds.
    fn take_spike_ns(&mut self) -> u64;
    /// Cumulative packets generated since last `init`.
    fn packets_generated(&self) -> u64;
    /// Cumulative packets dropped by fault injection since last `init`.
    fn packets_dropped(&self) -> u64;
    /// Cumulative packets corrupted by fault injection since last `init`.
    fn packets_corrupted(&self) -> u64;
}

impl<E> DynNic for crate::nic::VirtualNic<E>
where
    E: EventSink + Send,
{
    fn init(&mut self) -> flyby_core::Result<()> {
        flyby_core::Lifecycle::init(self)
    }
    fn shutdown(&mut self) -> flyby_core::Result<()> {
        flyby_core::Lifecycle::shutdown(self)
    }
    fn set_tick_context(&mut self, tick_ns: u64, clock_ns: u64) {
        crate::nic::VirtualNic::set_tick_context(self, tick_ns, clock_ns);
    }
    fn poll(&mut self, batch: &mut RawBatch) -> flyby_core::Result<usize> {
        flyby_net::NetworkSource::poll_batch(self, batch)
    }
    fn take_spike_ns(&mut self) -> u64 {
        crate::nic::VirtualNic::take_spike_ns(self)
    }
    fn packets_generated(&self) -> u64 {
        self.packets_generated
    }
    fn packets_dropped(&self) -> u64 {
        self.packets_dropped
    }
    fn packets_corrupted(&self) -> u64 {
        self.packets_corrupted
    }
}

/// Educational / interactive run controls.
#[derive(Debug, Clone, Default)]
pub struct EduControls {
    /// When `true`, [`SimScheduler::run`] returns after arming but before ticks;
    /// drive the loop with [`SimScheduler::step`].
    pub paused: bool,
    /// Break when the simulator clock reaches this value (nanoseconds).
    pub breakpoint_ns: Option<u64>,
    /// Break after this many ticks.
    pub breakpoint_tick: Option<u64>,
    /// Maximum ticks to execute in one `run`/`step` session (`None` = unlimited).
    pub max_steps: Option<u64>,
}

/// The simulation scheduler.
pub struct SimScheduler<E: EventSink> {
    scenario: Scenario,
    nics: Vec<Box<dyn DynNic>>,
    events: E,
    metrics: Arc<dyn MetricsCollector>,
    ring: Option<VirtualSharedMemory>,
    consumers: Vec<VirtualConsumer>,
    edu: EduControls,
    /// Last delivered batch (for educational packet inspection).
    last_batch: Option<RawBatch>,
    /// Internal clock retained across educational steps.
    clock: Option<SimClock>,
    wall_start: Option<Instant>,
    stats: SimStats,
    running: bool,
}

impl SimScheduler<NullEventSink> {
    /// Create a scheduler with a null event sink (no event storage overhead).
    pub fn new(scenario: Scenario) -> Self {
        Self::with_events(scenario, NullEventSink)
    }
}

impl<E: EventSink> SimScheduler<E> {
    /// Create a scheduler with a custom event sink.
    pub fn with_events(scenario: Scenario, events: E) -> Self {
        Self {
            scenario,
            nics: Vec::new(),
            events,
            metrics: Arc::new(NullCollector),
            ring: None,
            consumers: Vec::new(),
            edu: EduControls::default(),
            last_batch: None,
            clock: None,
            wall_start: None,
            stats: SimStats::default(),
            running: false,
        }
    }

    /// Attach a metrics collector.
    pub fn with_metrics(mut self, metrics: Arc<dyn MetricsCollector>) -> Self {
        self.metrics = metrics;
        self
    }

    /// Enable a virtual shared-memory ring between NICs and consumers.
    pub fn with_ring(mut self, ring: VirtualSharedMemory) -> Self {
        self.ring = Some(ring);
        self
    }

    /// Register a virtual consumer that drains the shared-memory ring.
    pub fn add_consumer(&mut self, consumer: VirtualConsumer) {
        self.consumers.push(consumer);
    }

    /// Replace educational controls.
    pub fn with_edu(mut self, edu: EduControls) -> Self {
        self.edu = edu;
        self
    }

    /// Mutable access to educational controls.
    pub fn edu_mut(&mut self) -> &mut EduControls {
        &mut self.edu
    }

    /// Register a virtual NIC to be driven by this scheduler.
    pub fn add_nic<N: DynNic + 'static>(&mut self, nic: N) {
        self.nics.push(Box::new(nic));
    }

    /// Inspect the last polled batch (educational mode).
    pub fn last_batch(&self) -> Option<&RawBatch> {
        self.last_batch.as_ref()
    }

    /// Current simulator clock reading, if a run is in progress.
    pub fn clock_ns(&self) -> Option<u64> {
        self.clock.as_ref().map(|c| c.now_ns())
    }

    /// Pause educational mode (further `run`/`resume` waits for `step`).
    pub fn pause(&mut self) {
        self.edu.paused = true;
    }

    /// Clear the pause flag.
    pub fn resume(&mut self) {
        self.edu.paused = false;
    }

    /// Run the scenario to completion and return aggregate statistics.
    pub fn run(&mut self) -> flyby_core::Result<SimStats> {
        self.begin()?;
        if self.edu.paused {
            // Educational: caller drives via `step`, then `finish_run`.
            return Ok(self.stats.clone());
        }
        while self.running {
            if !self.step()? {
                break;
            }
            if self.edu.paused {
                break;
            }
        }
        if !self.edu.paused {
            self.finish()?;
        }
        Ok(self.stats.clone())
    }

    /// Finalise a run that was driven via [`step`][Self::step].
    pub fn finish_run(&mut self) -> flyby_core::Result<SimStats> {
        self.finish()?;
        Ok(self.stats.clone())
    }

    /// Execute a single scheduler tick.
    ///
    /// Returns `true` if more ticks remain, `false` when the scenario is done
    /// or a breakpoint fired (check [`EduControls::paused`]).
    pub fn step(&mut self) -> flyby_core::Result<bool> {
        if !self.running {
            self.begin()?;
        }

        let tick_ns = self.scenario.tick_ns;
        let duration_ns = self.scenario.duration.as_nanos() as u64;
        let now_ns = self.clock.as_ref().expect("begin sets clock").now_ns();

        if now_ns >= duration_ns {
            self.running = false;
            return Ok(false);
        }

        if let Some(bp) = self.edu.breakpoint_ns {
            if now_ns >= bp {
                self.edu.paused = true;
                return Ok(false);
            }
        }
        if let Some(bp) = self.edu.breakpoint_tick {
            if self.stats.ticks >= bp {
                self.edu.paused = true;
                return Ok(false);
            }
        }
        if let Some(max) = self.edu.max_steps {
            if self.stats.ticks >= max {
                self.edu.paused = true;
                return Ok(false);
            }
        }

        let tick_wall_start = Instant::now();
        let batch_cap = self.scenario.traffic.batch_size.max(1);
        let payload = self.scenario.traffic.payload_size.max(1);
        let frame_size = 42 + payload;
        let mut batch = RawBatch::new(batch_cap, frame_size);

        let mut spike_ns = 0u64;
        let now_ns = self.clock.as_ref().expect("begin sets clock").now_ns();

        for nic in &mut self.nics {
            nic.set_tick_context(tick_ns, now_ns);
            let _ = nic.poll(&mut batch);
            spike_ns = spike_ns.saturating_add(nic.take_spike_ns());
        }

        // Push delivered packets into virtual shared memory.
        if let Some(ring) = self.ring.as_mut() {
            for (data, _meta) in batch.packets() {
                match ring.try_push(data) {
                    Ok(seq) => {
                        self.stats.slots_written += 1;
                        self.metrics.record_counter(&SimMetricKey::SinkWrites, 1);
                        self.events.emit(SimEvent {
                            clock_ns: now_ns,
                            kind: SimEventKind::SlotWritten {
                                ring: ring.name(),
                                seq,
                            },
                        });
                    }
                    Err(_) => {
                        self.stats.ring_overflows += 1;
                        self.events.emit(SimEvent {
                            clock_ns: now_ns,
                            kind: SimEventKind::QueueOverflow { ring: ring.name() },
                        });
                    }
                }
            }
            let occ = ring.occupancy();
            self.metrics
                .record_gauge(&SimMetricKey::RingOccupancy, occ);
            self.metrics
                .record_gauge(&SimMetricKey::QueueOccupancy, occ);
        }

        // Drain consumers.
        if let Some(ring) = self.ring.as_mut() {
            for consumer in &mut self.consumers {
                let read = consumer.drain(ring, usize::MAX);
                self.stats.slots_consumed += read as u64;
                for _ in 0..read {
                    self.events.emit(SimEvent {
                        clock_ns: now_ns,
                        kind: SimEventKind::ConsumerRead {
                            ring: ring.name(),
                            seq: consumer.reads(),
                        },
                    });
                }
            }
        }

        self.last_batch = Some(batch);
        self.stats.ticks += 1;

        let tick_duration_ns = tick_wall_start.elapsed().as_nanos() as u64;
        self.events.emit(SimEvent {
            clock_ns: now_ns,
            kind: SimEventKind::TickCompleted {
                tick: self.stats.ticks,
                duration_ns: tick_duration_ns,
            },
        });
        self.metrics.record_counter(&SimMetricKey::TickCount, 1);
        self.metrics
            .record_histogram(&SimMetricKey::TickDurationNs, tick_duration_ns as f64);

        // Advance virtual time by one tick plus any injected latency spikes.
        let next_ns = {
            let clock = self.clock.as_mut().expect("begin sets clock");
            if clock.is_virtual() {
                clock.advance_ns(tick_ns.saturating_add(spike_ns));
            }
            clock.now_ns()
        };

        self.snapshot_nic_stats();
        self.stats.clock_ns = next_ns;

        if next_ns >= duration_ns {
            self.running = false;
            return Ok(false);
        }
        Ok(true)
    }

    fn begin(&mut self) -> flyby_core::Result<()> {
        if self.running {
            return Ok(());
        }
        for nic in &mut self.nics {
            nic.init()?;
        }
        self.clock = Some(SimClock::new(self.scenario.clock_mode.clone()));
        self.wall_start = Some(Instant::now());
        self.stats = SimStats::default();
        self.running = true;

        self.events.emit(SimEvent {
            clock_ns: 0,
            kind: SimEventKind::SimulatorStarted {
                scenario: self.scenario.name.to_string(),
            },
        });
        Ok(())
    }

    fn finish(&mut self) -> flyby_core::Result<()> {
        self.snapshot_nic_stats();
        if let Some(start) = self.wall_start.take() {
            self.stats.elapsed = start.elapsed();
        }
        if let Some(clock) = self.clock.as_ref() {
            self.stats.clock_ns = clock.now_ns();
        }

        self.events.emit(SimEvent {
            clock_ns: self.stats.clock_ns,
            kind: SimEventKind::SimulatorStopped {
                ticks: self.stats.ticks,
                elapsed_ns: self.stats.elapsed.as_nanos() as u64,
            },
        });

        for nic in &mut self.nics {
            nic.shutdown()?;
        }
        self.running = false;
        Ok(())
    }

    fn snapshot_nic_stats(&mut self) {
        self.stats.packets_generated = 0;
        self.stats.packets_dropped = 0;
        self.stats.packets_corrupted = 0;
        for nic in &self.nics {
            self.stats.packets_generated += nic.packets_generated();
            self.stats.packets_dropped += nic.packets_dropped();
            self.stats.packets_corrupted += nic.packets_corrupted();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::clock::ClockMode;
    use crate::events::VecEventSink;
    use crate::fault::FaultSpec;
    use crate::nic::{VirtualNic, VirtualNicConfig};
    use crate::ring::VirtualSharedMemory;
    use crate::scenario::Scenario;
    use crate::traffic::{TrafficConfig, TrafficPattern};

    fn make_nic(batch_size: usize) -> VirtualNic<NullEventSink> {
        let cfg = VirtualNicConfig {
            traffic: TrafficConfig {
                pattern: TrafficPattern::FixedRate { pps: 1_000 },
                payload_size: 8,
                batch_size,
            },
            fault: FaultSpec::default(),
            ..VirtualNicConfig::default()
        };
        VirtualNic::new(cfg, NullEventSink)
    }

    #[test]
    fn run_without_nics_returns_zero_stats() {
        let mut sched = SimScheduler::new(Scenario::default());
        let stats = sched.run().unwrap();
        assert_eq!(stats.packets_generated, 0);
    }

    #[test]
    fn run_constant_rate_scenario_completes() {
        let scenario = Scenario::constant_rate();
        let mut sched = SimScheduler::new(scenario.clone());
        sched.add_nic(make_nic(scenario.traffic.batch_size));
        let stats = sched.run().unwrap();
        assert!(stats.ticks > 0, "should complete at least one tick");
    }

    #[test]
    fn ticks_match_duration_div_tick_ns() {
        let scenario = Scenario {
            duration: Duration::from_millis(10),
            tick_ns: 1_000_000,
            clock_mode: ClockMode::Virtual { start_ns: 0 },
            ..Scenario::default()
        };
        let expected_ticks = (scenario.duration.as_nanos() as u64) / scenario.tick_ns;
        let mut sched = SimScheduler::new(scenario);
        let stats = sched.run().unwrap();
        assert_eq!(stats.ticks, expected_ticks);
    }

    #[test]
    fn packets_generated_is_nonzero_with_nic() {
        let scenario = Scenario {
            duration: Duration::from_millis(5),
            tick_ns: 1_000_000,
            clock_mode: ClockMode::Virtual { start_ns: 0 },
            ..Scenario::default()
        };
        let mut sched = SimScheduler::new(scenario.clone());
        sched.add_nic(make_nic(64));
        let stats = sched.run().unwrap();
        assert!(stats.packets_generated > 0);
    }

    #[test]
    fn drop_fault_produces_nonzero_dropped_count() {
        let scenario = Scenario {
            duration: Duration::from_millis(5),
            tick_ns: 1_000_000,
            ..Scenario::packet_loss()
        };
        let cfg = VirtualNicConfig {
            fault: FaultSpec {
                drop_rate: 1.0,
                ..FaultSpec::default()
            },
            traffic: scenario.traffic.clone(),
            ..VirtualNicConfig::default()
        };
        let nic: VirtualNic<NullEventSink> = VirtualNic::new(cfg, NullEventSink);
        let mut sched = SimScheduler::new(scenario);
        sched.add_nic(nic);
        let stats = sched.run().unwrap();
        assert_eq!(
            stats.packets_dropped, stats.packets_generated,
            "100% drop rate should drop every packet"
        );
    }

    #[test]
    fn event_sink_receives_started_and_stopped() {
        let sink = VecEventSink::new();
        let scenario = Scenario {
            duration: Duration::from_millis(2),
            tick_ns: 1_000_000,
            clock_mode: ClockMode::Virtual { start_ns: 0 },
            ..Scenario::default()
        };
        let mut sched = SimScheduler::with_events(scenario, sink.clone());
        sched.run().unwrap();

        let events = sink.events();
        let started = events
            .iter()
            .filter(|e| matches!(e.kind, SimEventKind::SimulatorStarted { .. }))
            .count();
        let stopped = events
            .iter()
            .filter(|e| matches!(e.kind, SimEventKind::SimulatorStopped { .. }))
            .count();
        assert_eq!(started, 1);
        assert_eq!(stopped, 1);
    }

    #[test]
    fn multiple_nics_stats_are_summed() {
        let scenario = Scenario {
            duration: Duration::from_millis(5),
            tick_ns: 1_000_000,
            clock_mode: ClockMode::Virtual { start_ns: 0 },
            ..Scenario::default()
        };
        let mut sched = SimScheduler::new(scenario.clone());
        sched.add_nic(make_nic(64));
        sched.add_nic(make_nic(64));

        let single_stats = {
            let mut s = SimScheduler::new(scenario.clone());
            s.add_nic(make_nic(64));
            s.run().unwrap()
        };

        let dual_stats = sched.run().unwrap();
        assert!(dual_stats.packets_generated >= single_stats.packets_generated);
    }

    #[test]
    fn ring_and_consumer_move_packets() {
        let scenario = Scenario {
            duration: Duration::from_millis(5),
            tick_ns: 1_000_000,
            traffic: TrafficConfig {
                pattern: TrafficPattern::FullSpeed,
                batch_size: 8,
                payload_size: 8,
            },
            clock_mode: ClockMode::Virtual { start_ns: 0 },
            ..Scenario::default()
        };
        let mut sched = SimScheduler::new(scenario.clone()).with_ring(VirtualSharedMemory::new(
            "ring0",
            64,
            128,
        ));
        sched.add_nic(make_nic(8));
        sched.add_consumer(VirtualConsumer::new("c0"));
        let stats = sched.run().unwrap();
        assert!(stats.slots_written > 0);
        assert_eq!(stats.slots_consumed, stats.slots_written);
        assert_eq!(stats.ring_overflows, 0);
    }

    #[test]
    fn educational_step_advances_one_tick() {
        let scenario = Scenario {
            duration: Duration::from_millis(5),
            tick_ns: 1_000_000,
            clock_mode: ClockMode::Virtual { start_ns: 0 },
            ..Scenario::default()
        };
        let mut sched = SimScheduler::new(scenario).with_edu(EduControls {
            paused: true,
            ..EduControls::default()
        });
        sched.add_nic(make_nic(8));
        let stats = sched.run().unwrap();
        assert_eq!(stats.ticks, 0);

        assert!(sched.step().unwrap());
        assert_eq!(sched.stats.ticks, 1);
        assert!(sched.last_batch().is_some());
    }

    #[test]
    fn breakpoint_tick_pauses() {
        let scenario = Scenario {
            duration: Duration::from_millis(100),
            tick_ns: 1_000_000,
            clock_mode: ClockMode::Virtual { start_ns: 0 },
            ..Scenario::default()
        };
        let mut sched = SimScheduler::new(scenario).with_edu(EduControls {
            breakpoint_tick: Some(3),
            ..EduControls::default()
        });
        let _ = sched.run().unwrap();
        // After 3 ticks, breakpoint fires on the attempt to start tick 4?
        // Our check is `ticks >= bp` at start of step, so after completing 3
        // ticks the next step pauses before doing more work.
        // Actually run() loops while step returns true. When ticks==3 and we
        // try another step, breakpoint fires and returns false with paused.
        assert!(sched.edu.paused);
        assert!(sched.stats.ticks >= 3);
    }
}
